### PR TITLE
JavaScript snippets

### PR DESCRIPTION
**Pull request by ezeaniiandrew**
I added JavaScript snippets to the plugin

### CODE REVIEW

**Comment by bajrangCoder** [comment]
Some of these snippets are already available in snippets plugin and have you tested it?

Edit: Also add few docs about your snippets in plugin readme

**Comment by ezeaniiandrew** [comment]
Yes I've tested it and they all work fine. I thought I removed all duplicates but seems like I missed some. I'll recheck the snippets and remove the remaining duplicates.

**Comment by bajrangCoder** [comment]
> Yes I've tested it and they all work fine. I thought I removed all duplicates but seems like I missed some. I'll recheck the snippets and remove the remaining duplicates.

Ok, Alright 👍
But also add docs about your snippets shortcuts (in tabular form) for eg:
rcc - for react components 

Afterward I will merge it

**Comment by ezeaniiandrew** [comment]
Alright. I'll let you know when I'm done

**Pull request merged**
